name: Restart server

on: 
  push:
    branches:
     - testing

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
    - name: Restart Server
      shell: bash
      run: |
        curl --request POST \
        --url ${{ env.BASE_URL }}api/client/servers/${{ env.SERVER_ID }}/power \
        --header 'Accept: application/json' \
        --header 'Authorization: Bearer ${{ env.API_KEY }}' \
        --header 'Content-Type: application/json' \
        --data '{ "signal": "restart" }'
