name: Restart server

on: 
  push:
    branches:
     - testing

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTING_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV
          echo "INCLUDE_PATH=$SOURCEMOD_PATH/scripting/include" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler 1.10
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.10'

      - name: Compile test plugin
        run: |
          echo -e "\nCompiling test.sp..."
          spcomp -w234 -O2 -v2 -i $includePath -i $INCLUDE_PATH -o $GITHUB_WORKSPACE/test.smx test.sp
        working-directory: ${{ env.SCRIPTING_PATH }}/

      - name: Restart Server
        shell: bash
        run: |
          curl --request POST \
            --url ${{ secrets.BASE_URL }}api/client/servers/${{ secrets.SERVER_ID }}/power \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data '{ "signal": "restart" }'
